### ISSUE TITLE
Possible false positive in data race detection

### ISSUE THREAD

**Issue by Skilvingr** [rust-lang/miri#3361]
Hi, I think I've found a false positive in data race detection.

This is the example: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=347507781585b2326e01055a2ee26861: a simple SPSC ring buffer.
It works well as is, but uncommenting `L136` and commenting `L137`, a data race error is triggered.

The fact is, `L137` directly checks whether there is available data for the consumer, while `L136` relies upon an indirect check, that is the one within `available` function, at `L80`.

As far as I can imagine, both the solutions should work, being the check made before any access to underlying data, so I don't think it's an UB.
If not so, could you please explain me what's the difference between them two? Thanks!

**Comment by saethlin** [comment]
For anyone reading, this Playground link does not consistently report a data race because the playground always disables isolation: https://github.com/rust-lang/rust-playground/blob/c7d524cf831596a389c143263f68ca9b79b8a4a2/compiler/base/cargo-miri-playground#L6 and thus the threads here get scheduled differently from run-to-run.

**Comment by RalfJung** [comment]
> the threads here get scheduled differently from run-to-run.

That's actually still surprising, since the seed is fixed even without isolation. If it used `rand` then that would be truly random run-to-run, but Miri non-determinism remains fixed.

However, if the number of environment variables differs, then that changes the RNG stream requested by Miri (since we need a base address for each of their allocations) and that affects the scheduler.  Not sure if that might happen on the playground.

**Comment by RalfJung** [comment]
@Skilvingr Miri prints which two accesses it thinks are racing:
```
error: Undefined Behavior: Data race detected between (1) non-atomic write on thread `unnamed-1` and (2) non-atomic read on thread `unnamed-2` at alloc828+0x10. (2) just happened here
   --> src/main.rs:16:9
    |
16  |         (*self.0.get()).assume_init_ref()
    |         ^^^^^^^^^^^^^^^ Data race detected between (1) non-atomic write on thread `unnamed-1` and (2) non-atomic read on thread `unnamed-2` at alloc828+0x10. (2) just happened here
    |
help: and (1) occurred earlier here
   --> src/main.rs:69:17
    |
69  |                 self.buf.inner[self.local_idx].as_mut_ptr().write(v);
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Why do you think those can never happen without synchronization?

I don't recall ever seeing a false positive in the data race detector so I strongly assume that this is a true positive.

**Comment by Skilvingr** [comment]
> Note in particular that (*self.0.get()).assume_init_ref() might seem like it only creates a reference, but creating a &usize reference acts like a read. So that getter needs to be treated like it is doing a full read. IOW, pop_ref doesn't just check self.available(), it also reads from the buffer in case something is available, and that is what causes the race.

That makes a lot of sense, but, and I say this without knowing how Miri is actually implemented under the hood, should only the first check be considered? In the end if this check fails the read from the buffer doesn't happen at all.

However, I think the races can never happen because I am synchronising via atomic indices.

I mean, prod iterator writes something within index `n`, then updates its index with a Release ordering, so, if I've got it right, every write happened before that should be visible to all the other threads (i.e., data at index `n` is fully written for every other iterator).

Then comes the consumer.
Given that the only way for the consumer thread to read data is that its index is one less than the one of the producer (`L83` match case), and that the former is accessing the atomic index of the latter with an Acquire ordering, the data that the former reads is not only completely written, but also stands at most one location before the index that the producer is (eventually) currently writing.

So I can't figure out how a race could even happen this way.

**Comment by RalfJung** [comment]
There *is* a read in `inner_ref`. That's how Rust references work: when you create a shared reference (to a non-interior-mutable type), that's an implicit read. It doesn't matter if you subsequently explicitly read from that reference, the implicit read is always there.

This is the case to allow the compiler to insert reads where there were none, which is a really useful optimizations around loops.

In your case, this implicit reads races with the write in the other thread.

**Comment by Skilvingr** [comment]
Yes, I agree with the fact that there is a read inside `inner_ref`, but does that read still exist if `inner_ref` doesn't get called? I mean, don't I create that reference (and thus the subsequent read) only when I call `inner_ref`?

I've taken a look at the MIR (opt-level=3), but I keep on seeing the first bb `bb0` that does the check and unwinds if this check returns false. For what I get, the reference you are talking about is not created until `bb3`.

Should I go even down to LLVM IR or I am just misunderstanding MIR?

In any case, if you know a place where I can find more info about these implicit reads, I'd be glad to check it out by myself, without bothering you guys 😅.

**Comment by RalfJung** [comment]
The error has a backtrace of it being called.

Note that `then_some` always evaluates its argument. If you want a lazy version of that, use `then`. Is that the source of the confusion?

**Comment by Skilvingr** [comment]
Oh yes, sorry, my bad, I definitely should've read better the docs 😅.

Thank you very much indeed!
